### ISSUE TITLE
Class Diagram Refinement

### ISSUE THREAD

**Issue by jonderic** [ISANmus/INF2001-Patient-Buddy#11]
- To add missing data types for attributes.
- To add missing parameters and data types for methods.
- To double-check arrowhead dependencies.
- Removed Database entity from Class Diagram.

**Comment by khrnrn** [comment]
Data Type for attributes added. 
Parameters & data types for methods added.
Database removed from Class Diagram. 

Left with: Double-checking arrowhead dependencies.

**Comment by jonderic** [comment]
Corrected arrowheads for all dependency relationships.

**Comment by jonderic** [comment]
Corrected arrowheads for all dependency relationships. Issue closed.
